<a href="https://colab.research.google.com/github/shivaansh81001/Pytorch-IBM-/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch course

In [33]:
import torch
import numpy as np
import pandas as pd

Making 1D tensor

In [11]:
a = [2,3,4,5,6.2]
tens = torch.tensor(a)

data type

In [12]:
tens.dtype

torch.float32

explicit declaration


In [14]:
tens2 = torch.tensor(a,dtype=torch.int32)
tens2.dtype

torch.int32

FloatTensor (explicitly for floats)

In [15]:
b = torch.FloatTensor([1,2,3,4])
b.dtype

torch.float32

In [16]:
b.type()

'torch.FloatTensor'

type conversion

In [17]:
type1 = torch.tensor([1,2,3,4],dtype=torch.int32)
type2 = type1.type(torch.FloatTensor)
type2.type()

'torch.FloatTensor'

size, dimension and rank


In [18]:
b.size()

torch.Size([4])

In [19]:
b.ndimension()

1

1d to 2d
view(rows,cols)

In [24]:
b_col = b.view(-1,1)  #if we dont know the dimension of the vector we can use -1 to infer it
b_col

tensor([[1.],
        [2.],
        [3.],
        [4.]])

numpy conversion from or to tensor

In [28]:
np_array = np.array(b)    # using numpy
print(np_array)
type(np_array)

[1. 2. 3. 4.]


numpy.ndarray

In [29]:
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)
torch_tensor.type()

tensor([1., 2., 3., 4.])


'torch.FloatTensor'

In [32]:
back_to_np = torch_tensor.numpy()
type(back_to_np)

numpy.ndarray

pandas to/ from tensor

In [36]:
pandas_series = pd.Series([1,2,3,4,5])
pandas_series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [40]:
pandas_to_torch = torch.from_numpy(pandas_series.values)
print(pandas_to_torch.type())
pandas_to_torch

torch.LongTensor


tensor([1, 2, 3, 4, 5])

tensor to list

In [44]:
a = pandas_to_torch.tolist()
print(a)
type(a)

[1, 2, 3, 4, 5]


list

NOTE: indvidual values of a tensor are also tensors

In [46]:
pandas_to_torch[0]

tensor(1)

to return a python number istead of tensor use .item()

In [48]:
pandas_to_torch[0].item()

1